name: Create Code JSON

on:
  push:
    branches:
      - main
    paths:
      - "data/raw/**"
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 6' # https://crontab.guru/#0_13_*_*_6

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  combine-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          version: "latest"

      - name: Running combine script to create code.json
        run: |
          uv run python main.py --combine --output data/

      - name: Upload code.json file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: code-json
          path: data/code.json
          retention-days: 1

      - name: Running combine script to create privateid-mapping.csv
        run: |
          uv run python main.py --generate-csv

      - name: Upload private id mapping file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: privateid-mapping
          path: data/privateid_mapping.csv
          retention-days: 1

  commit-changes:
    needs: combine-data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download code.json artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: code-json
          path: data/

      - name: Download code.json artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: privateid-mapping
          path: data/

      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ vars.GIT_APP_OCIO_SHAREIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_OCIO_SHAREIT_PRIVATE_KEY }}

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.email "${{ vars.GIT_APP_OCIO_SHAREIT_APP_ID }}+${{ vars.GIT_APP_OCIO_SHAREIT_APP_NAME }}[bot]@users.noreply.github.com"
          git config --global user.name "${{ vars.GIT_APP_OCIO_SHAREIT_APP_NAME }}[bot]"
          git config remote.origin.url 'https://${{ vars.GIT_APP_OCIO_SHAREIT_APP_ID }}:${{ env.GH_TOKEN }}@github.com/CDCgov/ShareIT-Act.git'
          git add data/code.json
          git add data/privateid_mapping.csv
          if ! git diff-index --quiet HEAD; then
            git commit --allow-empty -m "Automate update of code.json - $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push
          fi
